general.import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7
blur = true

[window.padding]
x = 10
y = 10

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
bold.style = "Bold"
bold_italic.style = "Bold Italic"
italic.style = "Italic"

size = 14


