{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}


{{ if  (eq .chezmoi.os "linux" "darwin")  -}}

{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

fzf-git:
  type: git-repo
  url: https://github.com/junegunn/fzf-git.sh.git
  refreshPeriod: 168h


.oh-my-zsh:
  type: archive
  url: "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  stripComponents: 1
  refreshPeriod: 168h
  exact: false

{{- $powerlevel10kVersionTag := (gitHubLatestRelease "romkatv/powerlevel10k").TagName }}
.oh-my-zsh/custom/themes/powerlevel10k:
  type: archive
  url: "https://github.com/romkatv/powerlevel10k/archive/{{ $powerlevel10kVersionTag }}.tar.gz"
  exact: false
  stripComponents: 1

.oh-my-zsh/custom/plugins/zsh-autosuggestions:
  type: archive
  {{ $zshAutoSuggestionsRevision := includeTemplate "get-github-head-revision" (list "zsh-users/zsh-autosuggestions" $cache) }}
  url: "https://github.com/zsh-users/zsh-autosuggestions/archive/{{ $zshAutoSuggestionsRevision }}.tar.gz"
  stripComponents: 1
  exact: true

.oh-my-zsh/custom/plugins/fast-syntax-highlighting:
  type: archive
  url: "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  stripComponents: 1
  exact: true
  refreshPeriod: 168h

.config/fsh/catppuccin-mocha.ini:
  type: file
  url: https://github.com/catppuccin/zsh-fsh/raw/main/themes/catppuccin-mocha.ini
  refreshPeriod: 168h

.config/fsh/catppuccin-latte.ini:
  type: file
  url: "https://github.com/catppuccin/zsh-fsh/raw/main/themes/catppuccin-latte.ini"
  refreshPeriod: 168h

.config/gitalias/gitalias.txt:
  type: file
  {{ $gitaliasRevision := includeTemplate "get-github-head-revision" (list "GitAlias/gitalias" $cache) }}
  url: "https://github.com/GitAlias/gitalias/raw/{{ $gitaliasRevision }}/gitalias.txt"

.vim/pack/vendor/start/alker0/chezmoi.vim:
  type: git-repo
  url: https://github.com/alker0/chezmoi.vim.git
  refreshPeriod: 168h
.vim/pack/vendor/start/nerdtree:
  type: git-repo
  url: https://github.com/preservim/nerdtree.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-terraform:
  type: git-repo
  url: https://github.com/hashivim/vim-terraform.git
  refreshPeriod: 168h
.vim/pack/plugins/start/nerdtree-git-plugin:
  type: git-repo
  url: https://github.com/Xuyuanp/nerdtree-git-plugin.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-devicons:
  type: git-repo
  url: https://github.com/ryanoasis/vim-devicons.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-nerdtree-syntax-highlight:
  type: git-repo
  url: https://github.com/tiagofumo/vim-nerdtree-syntax-highlight.git
  refreshPeriod: 168h
.vim/pack/plugins/start/fzf.vim:
  type: git-repo
  url: https://github.com/junegunn/fzf.vim.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-surround:
  type: git-repo
  url: https://github.com/tpope/vim-surround.git
  refreshPeriod: 168h
.vim/pack/plugins/start/editorconfig-vim:
  type: git-repo
  url: https://github.com/editorconfig/editorconfig-vim.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-fugitive:
  type: git-repo
  url: https://github.com/tpope/vim-fugitive.git
  refreshPeriod: 168h
.vim/pack/plugins/start/syntastic:
  type: git-repo
  url: https://github.com/vim-syntastic/syntastic.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-airline:
  type: git-repo
  url: https://github.com/vim-airline/vim-airline.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-airline-themes:
  type: git-repo
  url: https://github.com/vim-airline/vim-airline-themes.git
  refreshPeriod: 168h
.vim/pack/plugins/start/nerdcommenter:
  type: git-repo
  url: https://github.com/preservim/nerdcommenter.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-easymotion:
  type: git-repo
  url: https://github.com/easymotion/vim-easymotion.git
  refreshPeriod: 168h
.vim/pack/plugins/start/commentary:
  type: git-repo
  url: https://tpope.io/vim/commentary.git
  refreshPeriod: 168h
.vim/pack/plugins/start/vim-go:
  type: git-repo
  url: https://github.com/fatih/vim-go.git
  refreshPeriod: 168h
.vim/pack/plugins/opt/chezmoi.vim:
  type: git-repo
  url: https://github.com/alker0/chezmoi.vim
  refreshPeriod: 168h
# .tmux/plugins/tpm:
#   type: git-repo
#   url: https://github.com/tmux-plugins/tpm
#   refreshPeriod: 168h


{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}

{{ $fontDir }}/MesloLGS NF Regular.ttf:
  type: file
  url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf
  refreshPeriod: 168h
{{ $fontDir }}/MesloLGS NF Bold.ttf:
  type: file
  url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf
  refreshPeriod: 168h
{{ $fontDir }}/MesloLGS NF Italic.ttf:
  type: file
  url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf
  refreshPeriod: 168h
{{ $fontDir }}/MesloLGS NF Bold Italic.ttf:
  type: file
  url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf
  refreshPeriod: 168h

{{- end -}}
