#!/bin/bash

# Executables: binbundle
gem install binbundle -v '1.0.9'

# Executables: bundle, bundler
gem install bundler -v '2.5.11'

# Executables: rdbg
gem install debug -v '1.9.1'

# Executables: erb
gem install erb -v '4.0.3'

# Executables: irb
gem install irb -v '1.13.1'

# Executables: racc
gem install racc -v '1.7.3'

# Executables: rake
gem install rake -v '13.1.0'

# Executables: rbs
gem install rbs -v '3.4.0'

# Executables: rdoc, ri
gem install rdoc -v '6.6.3.1'

# Executables: syntax_suggest
gem install syntax_suggest -v '2.0.0'

# Executables: typeprof
gem install typeprof -v '0.21.9'
