---
prSections:
  - title: Mine
    filters: is:open author:@me
  - title: Mentioned
    filters: is:open mentions:@me archived:false
  - title: My Review
    filters: is:open user-review-requested:@me archived:false status:success
  - title: Team Review
    filters: is:open -author:@me team-review-requested:ncr-digital-banking/ncr-dbk-sre archived:false status:success
  - title: TF v1 Upgrade
    filters: is:open is:pr archived:false user:ncr-digital-banking  author:app/renovate "update hashicorp/terraform docker tag to v1"

issuesSections:

defaults:
  layout:
    prs:
      base:
        hidden: false
  preview:
    open: false
    width: 75
  prsLimit: 50
  issuesLimit: 20
  view: prs

repoPaths:
  ncr-digital-banking/*: ~/Documents/60\ Professional/61\ Projects/61.00\ Repositories/*

pager:
  diff: delta

keybindings:
  prs:
    - key: e
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          bash --noprofile --norc
        '
    - key: v
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          vim .
        '
    - key: z
      command: >
        cd {{.RepoPath}} &&
        code . &&
        gh pr checkout {{.PrNumber}}

    - key: t
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}} &&
        gittower {{.RepoPath}}
