---
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Ready for My Review
    filters: is:open is:pr user-review-requested:@me archived:false status:success
  - title: Ready for Team Review
    filters: is:open is:pr team-review-requested:ncr-digital-banking/ncr-dbk-sre archived:false status:success

issuesSections:

defaults:
  preview:
    open: false
    width: 50
  prsLimit: 50
  issuesLimit: 20
  view: prs

repoPaths:
  ncr-digital-banking/*: ~/Documents/60 Professional/61 Projects/61.00 Repositories/*

pager:
  diff: delta

keybindings:
  prs:
    - key: v
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          vim -c ":DiffviewOpen master...{{.HeadRefName}}"
        '
    - key: c
      command: >
        cd {{.RepoPath}} &&
        code . &&
        gh pr checkout {{.PrNumber}}
