prSections:
- title: My Pull Requests
  filters: is:open author:@me
- title: Ready for Review
  filters: is:open is:pr team-review-requested:ncr-digital-banking/ncr-dbk-sre archived:false status:success
issuesSections:
defaults:
  preview:
    open: false
    width: 50
  prsLimit: 50
  issuesLimit: 20
  view: prs
