# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Review
    filters: is:open review-requested:@me
    layout:
      repo:
        width: 6
  - title: Commented
    filters: commenter:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
    limit: 10

issuesSections:
  - title: Creator
    filters: is:open author:@me
  - title: Commenter
    filters: is:open commenter:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

defaults:
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      repoName:
        grow: true
        width: 10
        hidden: false
      base:
        hidden: false
  refetchIntervalMinutes: 10

keybindings:
  universal:
    - key: z
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: O
      builtin: checkout
    - key: C
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":silent Octo pr edit {{.PrNumber}}"
        '
    - key: b
      command: cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup | command jq -rcj '.statusCheckRollup.[] | select(.context == "buildkite/mono") | .targetUrl' | xargs open
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

repoPaths:
  ncr-digital-banking/*: ~/Code/DI

theme:
  colors:
    # Mocha Blue
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
    # Latte Blue
    # text:
    #   primary: "#4c4f69"
    #   secondary: "#1e66f5"
    #   inverted: "#dce0e8"
    #   faint: "#5c5f77"
    #   warning: "#d20f39"
    #   success: "#40a02b"
    # background:
    #   selected: "#ccd0da"
    # border:
    #   primary: "#1e66f5"
    #   secondary: "#bcc0cc"
    #   faint: "#ccd0da"
  ui:
    sectionsShowCount: true
    table:
      compact: false
pager:
  diff: delta
