prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    limit: 10
  - title: Needs My Review
    filters: is:open review-requested:@me
    limit: 10
  - title: Involved
    filters: is:open involves:@me -author:@me
    limit: 10

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

defaults:
  preview:
    open: true
    width: 84
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: O
      builtin: checkout
    - key: m
      command: gh pr merge --admin --repo {{.RepoName}} {{.PrNumber}
    - key: C
      name: code review
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":silent Octo pr edit {{.PrNumber}}"
        '
    - key: a
      name: lazygit add
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      name: approve
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

repoPaths:
  # TODO: Update paths
  # ncr-digital-banking/*: ~/Documents/60\ Professional/61\ Projects/61.00\ Repositories/*

theme:
  colors:
    # Mocha Blue
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
    # Latte Blue
    # text:
    #   primary: "#4c4f69"
    #   secondary: "#1e66f5"
    #   inverted: "#dce0e8"
    #   faint: "#5c5f77"
    #   warning: "#d20f39"
    #   success: "#40a02b"
    # background:
    #   selected: "#ccd0da"
    # border:
    #   primary: "#1e66f5"
    #   secondary: "#bcc0cc"
    #   faint: "#ccd0da"
  ui:
    table:
      showSeparator: true

pager:
  diff: delta
