# GitHub Enterprise Importer (gh gei extension)
^([/\w\.]+\/)?gh gei\b
conf.gei

^([/\w\.]+\/)?gh-gei\b
conf.gei

# Go
^([/\w\.]+\/)?go test\b
conf.gotest

# Terraform
^([/\w\.]+\/)?terraform\b
conf.terraform

# Terragrunt
^([/\w\.]+\/)?terragrunt\b
conf.terraform

# Terragrunt
^([/\w\.]+\/)?python3\b
conf.python-logging
